# Generated by Django 4.2.1 on 2024-03-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_clients_created_by_alter_projects_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.projects'),
        ),
    ]
