# Generated by Django 5.0.3 on 2024-03-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_clients_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='projects',
        ),
        migrations.AddField(
            model_name='projects',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rest.clients'),
            preserve_default=False,
        ),
    ]
